name: bookvoed
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_barcode_scanner: ^0.1.7
  progress_dialog: ^1.2.0
  http: ^0.12.0+2
  sqflite: any
  path_provider: any
  flutter_launcher_icons: ^0.7.3
  shared_preferences: ^0.5.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
